services:
  amqp_iotda:
    build:
      context: .
      dockerfile: Dockerfile.amqp_iotda.local
    container_name: pvr_amqp_iotda
    volumes:
      - ./apps/amqp_iotda:/app/apps/amqp_iotda
      - ./config:/app/config
      - ./db:/app/db
      - ./helper:/app/helper
      - ./models:/app/models
      - ./repository:/app/repository
    env_file:
      - .env.amqp_iotda.local
  
  platfrom:
    build:
      context: .
      dockerfile: Dockerfile.platform.local
    container_name: pvr_platform
    ports:
      - 4002:4002
    volumes:
      - ./apps/platform:/app/apps/platform
      - ./config:/app/config
      - ./db:/app/db
      - ./helper:/app/helper
      - ./middleware:/app/middleware
      - ./models:/app/models
      - ./repository:/app/repository
      - ./migration:/app/migration
    env_file:
      - .env.platform.local
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15-alpine
    container_name: postgres-pvr
    restart: always
    environment:
      POSTGRES_DB: pvr_platform
      POSTGRES_USER: adriansyah
      POSTGRES_PASSWORD: adriansyahganteng
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

