FROM golang:1.24-alpine

WORKDIR /app

COPY ./apps/mqtt /app/apps/mqtt
COPY .air.toml.mqtt /app/.air.toml
COPY ./config /app/config
COPY ./db /app/db
COPY go.work.mqtt /app/go.work


# Set working directory to the specific service
WORKDIR /app/apps/mqtt

RUN apk add --no-cache git

RUN go work sync && go mod tidy

RUN go install github.com/air-verse/air@v1.62.0

WORKDIR /app

CMD ["air", "-c", ".air.toml"]
